### PR TITLE
Updates to Readme & some old changes from @crdunwel

### PR DESCRIPTION
**Pull request by georgiamoon**
Not sure who to point this to but maybe @crdunwel will be able to review? There are some commits from 2015-2016 that are wrapped up in here, and I just made some edits to the readme.md based on help from @seamustuohy getting the code to run. Hope this is helpful!

### CODE REVIEW

**Comment by jsfenfen** [comment]
Thanks, @georgiamoon. This repo has been neglected for a while, really glad you were able to make it work. Can you say what time periods you've got it working on--in other words, have you tested this on the most recent Senate report? I think that's Oct/2016-Mar 2017?

**Comment by georgiamoon** [comment]
@jsfenfen I'm running it now, and it's been working, but it's pretty fragile around blank pages. I'm running from `run.py` so the first few times I ran into some bumps with a few blank pages, I'm trying  now to break it up at the blanks, and then I'll combine the completed, cleaned csvs at the end. more notes on that coming soon!

**Comment by georgiamoon** [comment]
FYI -- I'm adding my contributions to the propublica fork here: https://github.com/propublica/senate_disbursements

**Comment by jsfenfen** [comment]
That's great, will try to synch this fork at some point.

**Pull request closed without merging**
